export { ReactComponent as PolkadotSVG } from './images/icons/polkadot.svg'
export { ReactComponent as SubWalletSVG } from './images/icons/subwallet.svg'
export { ReactComponent as TalismanSVG } from './images/icons/talisman.svg'
export { ReactComponent as EnkryptSVG } from './images/icons/enkrypt.svg'
export { ReactComponent as NovaIcon } from './images/icons/nova.svg'
